# Generated by Django 5.1.2 on 2024-11-17 14:36

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=60)),
                ('title_ru', models.CharField(max_length=60)),
                ('season', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('episode', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age', models.CharField(max_length=3)),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('description', models.CharField()),
                ('main_genre', models.CharField(choices=[('series', 'Сериалы'), ('anime', 'Аниме'), ('films', 'Фильмы')], default='series', max_length=50)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('Comedy', 'Комедии'), ('Cartoons', 'Мультфильмы'), ('Horror', 'Ужасы'), ('Fantastic', 'Фантастика'), ('Thrillers', 'Триллеры'), ('Fighters', 'Боевики'), ('Melodramas', 'Мелодрамы'), ('Detectives', 'Детективы'), ('Adventures', 'Приключения'), ('Fantasy', 'Фэнтези'), ('Military', 'Военные'), ('Family', 'Семейные'), ('Anime', 'Аниме'), ('Historical', 'Исторические'), ('Dramas', 'Драмы'), ('Documentary', 'Документальные'), ("Children's", 'Детские'), ('Crime', 'Криминал'), ('Biographies', 'Биографии'), ('Westerns', 'Вестерны'), ('Film Noir', 'Фильмы-нуар'), ('Sports', 'Спортивные'), ('Real TV', 'Реальное ТВ'), ('Short films', 'Короткометражки'), ('Musical', 'Музыкальные'), ('Musicals', 'Мюзиклы'), ('Talk show', 'Ток-шоу'), ('Games', 'Игры')], default='Comedy', max_length=50)),
            ],
        ),
    ]
