# Generated by Django 5.1.2 on 2024-11-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
