# Generated by Django 5.1.2 on 2024-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelvideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
