# Generated by Django 5.1.2 on 2024-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_modelvideo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
